name: book_app_f
description: "Book Readers - Tu biblioteca digital"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  bloc: ^9.0.0
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  injectable: ^2.5.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  meta: ^1.16.0
  jwt_decoder: ^2.0.1
  socket_io_client: ^3.1.2
  window_manager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  icons_launcher: ^2.1.7  # Paquete para generar iconos

# Configuración de icons_launcher
icons_launcher:
  image_path: "assets/images/logo.png"  # Usas logo.png según tus assets
  platforms:
    android:
      enable: true
      image_path: "assets/images/logo.png"
      # Android adaptive icons (moderno)
      adaptive_background_color: "#8B5CF6"  # Tu color morado
      adaptive_foreground_image: "assets/images/logo.png"
      adaptive_round_image: "assets/images/logo.png"
      adaptive_monochrome_image: "assets/images/logo.png"

    ios:
      enable: true
      image_path: "assets/images/logo.png"

    web:
      enable: true
      image_path: "assets/images/logo.png"
      favicon_path: "assets/images/logo.png"

    windows:
      enable: true
      image_path: "assets/images/logo.png"
      icon_size: 256

    macos:
      enable: true
      image_path: "assets/images/logo.png"

    linux:
      enable: true
      image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_cover.png
    - assets/images/logo.png
    - assets/images/logos.png